### PR TITLE
(SCT-205) Fix project name mismatch issue

### PR DESCRIPTION
**Pull request by olatt**

### CODE REVIEW

**Comment by LivingInSyn** [comment]
@olatt does this PR do anything besides just adding that option? Can we default it to something more sane?

**Comment by olatt** [comment]
> @olatt does this PR do anything besides just adding that option? Can we default it to something more sane?

I was testing using these two inputs.
```
snykProject: ${{ github.event.repository.name }}
repoName: 'https://github.com/${{github.repository}}'
```
@LivingInSyn We could add the project name and repo url in the default args instead of having to specify it in inputs.

**Comment by LivingInSyn** [comment]
Just seems like we should default to those env vars. I'm totally cool with overriding them with `INPUT_REPONAME` though

**Comment by olatt** [comment]
@LivingInSyn Changed the repo URL value to be set in default env vars.

**Review by jelinwils — APPROVED** [review]

**Pull request merged**
